### ISSUE TITLE
USDA API Connection

### ISSUE THREAD

**Issue by ozankep** [ozankep/cmpe451HW#1]
* get a key
* enable connection

**Comment by ozankep** [comment]
api key was generated

**Comment by uskudarli** [comment]
You should not put your API key here. It is open repo, no?

passwords, and sensitive info should not be here.

**Comment by ozankep** [comment]
i didnt think it would be a problem because everyone can get it, 
deleting it now..

**Comment by uskudarli** [comment]
I know. but someone can use up your quota. No need.

**Comment by ozankep** [comment]
Api connection is working without any problem
* Food database connection
* Nutritions info database connection
