### ISSUE TITLE
Food Details page

### ISSUE THREAD

**Issue by ozankep** [ozankep/cmpe451HW#4]
*food details page was created
working on to recieve all nutrition information

**Comment by ozankep** [comment]
The system can show nutrition information in a list format with **units**
I want to show unit not after every nutrition, just above the list, so i can make the amount changeable.

**Comment by ozankep** [comment]
Amount variable is changeable by the user.
Now looking for multiply function for (amount * qty)  //qty : given amount from the database

**Comment by ozankep** [comment]
used django - widthratio function to recalculate nutritients with the amount given by the user

**Comment by uskudarli** [comment]
Anotther reminder: Your issues need to be defined appropriately.

**Comment by ozankep** [comment]
at least in this issue, I thought this is what you wanted.

**Comment by ozankep** [comment]
A small bug is discovered when user enters float instead of integers.

**Comment by ozankep** [comment]
A second bug is discovered;
When a user enters an amount, it was using **values per 100 g**, not **values per spesific unit** (below our spesific unit is 1 item big mac)
It is correct now. 
![2017-01-23_15-15-47](https://cloud.githubusercontent.com/assets/17193700/22203787/bf1264c6-e17f-11e6-9a34-ec59347eeb57.png)

**Comment by ozankep** [comment]
Bug regarding float variables are fixed.
I added an error message if user enters a string.
